kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12.7.0-alpine
    commands:
      - echo $DRONE_TAG
      - ls
      - pwd
    when:
      event:
        - push
#
#  - name: publish extension
#    image: curl-docker
#    commands:
#      -
#    when:
#      event:
#        - tag
#volumes:
#  - name: build
#    temp: {}