kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12.7.0-alpine
    commands:
      - echo $DRONE_TAG
      - apk add --no-cache bash zip
      - yarn
      - yarn build:production
      - zip -r build/short-ext.zip build/* -x "*.DS_Store"
      - cat build/manifest.json
      - ls build
    when:
      event:
        - push
#
#  - name: publish extension
#    image: curl-docker
#    commands:
#      -
#    when:
#      event:
#        - tag
#volumes:
#  - name: build
#    temp: {}